here.user.id = HERE-d12ba421-a9e0-4186-932b-f73963681ccd
here.client.id = 7C04llDLbYtySCiw9EnT
here.access.key.id = wtwzmWpiLelM_6syxvMqFQ
here.access.key.secret = b7WrYeLusbcUzJNJcmp_aGvBlZmmmR7vB18otH5J9Sn0ybOT_IZpMNKQeND9QUpeHAHH2F8CipHCPMblacg6dw
here.token.endpoint.url = https://account.api.here.com/oauth2/token
here.api.key = 8ZI4V33ffRb_xelYDekkMJL4pAVM47fCa2eb82sog6s