// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH1ciOuOLVHKjgfaxLempr30PfblTdVEg',
    appId: '1:592385846462:android:c05ed334c8976de1b382ef',
    messagingSenderId: '592385846462',
    projectId: 'car-app-5b455',
    storageBucket: 'car-app-5b455.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDki7FqzUbUAoc4BO-c8fp7aAUa-OppSOk',
    appId: '1:592385846462:ios:16f35ccda611c790b382ef',
    messagingSenderId: '592385846462',
    projectId: 'car-app-5b455',
    storageBucket: 'car-app-5b455.appspot.com',
    androidClientId: '592385846462-koarolihitsb2ajvgbab8ijhbkv46n9u.apps.googleusercontent.com',
    iosClientId: '592385846462-4kk7jjctp9ifq5rvgda50ssmcivccsb4.apps.googleusercontent.com',
    iosBundleId: 'com.kadodata.journeycost',
  );
}
